---
- name: Initialize WSL2 Ubuntu Dev Environment
  hosts: localhost
  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: github_user_name
      prompt: "Git global user.name"
      default: ""
      private: false
    - name: github_user_email
      prompt: "Git global user.email"
      default: ""
      private: false

  roles:
    - { role: base, become: true }
    - { role: shell }
    - { role: homebrew }
    - { role: sdkman_java }
    - { role: nvm_node }
    - { role: python, become: true }
    - { role: rust }
    - { role: docker, become: true }
    - { role: vscode, become: true }
