---
- name: Check if NVM is installed
  ansible.builtin.stat:
    path: "/home/{{ ansible_facts['ansible_user_id'] }}/.nvm/nvm.sh"
  register: nvm_node_installed

- name: Download NVM installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh
    dest: /tmp/nvm_install.sh
    mode: '0755'
  when: not nvm_node_installed.stat.exists

- name: Install NVM
  ansible.builtin.shell: >
    set -o pipefail &&
    bash /tmp/nvm_install.sh
  when: not nvm_node_installed.stat.exists
  changed_when: true

- name: Ensure NVM init is sourced in .zshrc
  ansible.builtin.blockinfile:
    path: "/home/{{ ansible_facts['ansible_user_id'] }}/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED NVM BLOCK"
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    create: true

- name: Install Node versions via NVM
  ansible.builtin.shell: >
    bash -c 'export NVM_DIR=/home/{{ ansible_facts['ansible_user_id'] }}/.nvm &&
    source $NVM_DIR/nvm.sh &&
    nvm install {{ item }}'
  args:
    creates: "/home/{{ ansible_facts['ansible_user_id'] }}/.nvm/versions/node/v{{ item }}*"
  loop: "{{ node_versions }}"
  changed_when: true

- name: Set default Node version
  ansible.builtin.shell: >
    bash -c 'export NVM_DIR=/home/{{ ansible_facts['ansible_user_id'] }}/.nvm &&
    source $NVM_DIR/nvm.sh &&
    nvm alias default {{ default_node_version }}'
  changed_when: true
