---
- name: Install Python system packages
  ansible.builtin.apt:
    name: "{{ python_apt_packages }}"
    state: present

- name: Ensure pipx path is set up
  become: false
  ansible.builtin.command: pipx ensurepath
  environment:
    PATH: "/home/{{ USERNAME }}/.local/bin:{{ ansible_env.PATH }}"
  changed_when: false

- name: Install common Python tooling via pipx
  become: false
  community.general.pipx:
    name: "{{ item }}"
    state: present
  loop:
    - poetry
    - black
    - ruff
